version: 2.1
orbs:
  node: circleci/node@4
jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
  release:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: cd dist && npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - master
          context:
            - npm
          requires:
            - test
